/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Crypto-Conditions"
 * 	found in "CryptoConditions.asn"
 */

#ifndef	_RsaFingerprintContents_H_
#define	_RsaFingerprintContents_H_


#include "asn_application.h"

/* Including external dependencies */
#include <OCTET